### ISSUE TITLE
Rummy Nights v0.3 - roadmap, brainstorming and 0.2 retrospective

### ISSUE THREAD

**Issue by arqalite** [arqalite/rummy-nights#91]
As v0.2 is almost done, we need to create a plan for 0.3. 

0.2 brings a ton of improvements to general UX, app stability and performance, while also adding useful features (tile bonus, dealer tracking, templates). The app is quite stable and very much usable for playing RTR (Romanian Tile Rummy) with very minor grievances regarding the experience during dogfooding (which is constant - we use the app whenever we play rummy together with friends or by ourselves). So I believe the focus should be on nice-to-haves, like customizability.

For our intents and purposes, the app does what we want, but we want it to be accessible to other people's way of playing the game.
We remain focused only on RTR for now.

- [x] Let users change the max score.
- [x] Let users change the tile bonus value (we are aware of people playing with 25 instead of 50).

General app nice-to-haves:
- [x] Add settings menu (#32)
~~Add dark mode (#31)~~
